# language: python
# branches:
#   only:
#   - source
# install:
# - pip install pelican ghp-import Markdown pillow
# script:
# - make publish github
# env:
#   global:
#   - secure: 5/VbTbTKavIePum7b/OvbqndyRWw/LOVlvjVCmAk/1VVFY3Hs7XV/fD2Xw9BR+sQPRiYJuW5Wd4oijXS5zvANZRTbaF9vi9KPssDf9UzC9KbdD2q/CHyK0RWvUkf0LQsxWGmGPfNGNq+HJ4vRcwOpskMvkqLXQLWtzHmEwNR5UZ9vopZurR61+XBs9CfTjpgcj2xc9BahPA0HSgRqcwiQklavWxMhgL0MDRKw/ISJke7TppFas0V61hvgV8/c94athqhrwggPUzKx9OvMqajnJs3TAaQnZ1Vkxc3X9Jod88n9M8S8VvqJ57oMFGGNGTHd0hB0VTsEY/EE5A5vSCN7/fjA5FADdx1xbQ74utjmVCSVJEktVT7ANwJ05e2cZNATgSnYqs+WSD1Tg0qStQkTB/XMhGmraGZoZbTPMl9BM0jD3mtXhHpzLW/F5eJxSnDTciPl3ufr3SO05UURR0I2vDgF20TqKGT08+b8zqYUjZOf94Bz9FLe6FftvqncRGVKEeGlhQ5WAS8FYm8Gp66rstF1afiFhJapxuiU/3ehQNS7K000NtmbryJFC4DPB9DvrHmhytp0YoMK8+DDlEwAWy+JdeuMrBAZUdVEaCyD6Ar8FNzi1SAMzyy3vr6qQ74o+98eo54XMVgKx7kAeUg3fcb8zmH4WkDtENzo4fK8lY=


version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/dmuhs.github.io
    branches:
      only:
        - source
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install --user pelican ghp-import Markdown pillow
      - run:
          name: deploy on Github pages
          command: make publish github
